version: '3.1'

services:
  postgres:
    container_name: kmg-postgres
    image: postgres:latest
    ports:
      - '5437:5432'
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: kmg
      POSTGRES_PASSWORD: 1234
    networks:
      - backend

  pgadmin:
    links:
      - postgres:postgres
    container_name: pgadmin
    image: dpage/pgadmin4
    ports:
      - '8080:80'
    volumes:
      - /data/pgadmin:/root/.pgadmin
    env_file:
      - .env.development
    networks:
      - backend

  redis:
    container_name: kmg-redis
    image: redis:latest
    ports:
      - '6380:6379'
    networks:
      - backend
    command: redis-server --appendonly yes

  minio:
    container_name: kmg-minio
    image: minio/minio:latest
    ports:
      - '9000:9000'
      - "9099:9099"
    networks:
      - backend
    environment:
      MINIO_ROOT_USER: kmg
      MINIO_ROOT_PASSWORD: mgko0502
    volumes:
      - ./data:/data
    command: server --address ":9099" --console-address ":9000" /data

networks:
  backend:
    driver: bridge
