version: '3'

services:
  postgres:
    container_name: MVpostgres
    image: postgres:14
    command: ["postgres", "-c", "log_statement=mod", "-c", "log_destination=stderr", "-c", "log_min_duration_statement=50"]  # "log_duration=on"  "log_min_duration_statement=50]
    ports:
      - '5432:5432'
    volumes:
      - /data/postgres:/data/postgres
    env_file:
      - .env.development
    networks:
      - postgres

  pgadmin:
    links:
      - postgres:postgres
    container_name: MVpgadmin
    image: dpage/pgadmin4
    ports:
      - '8080:80'
    volumes:
      - /data/pgadmin:/root/.pgadmin
    env_file:
      - .env.development
    networks:
      - postgres

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"

  redis-commander:
    image: rediscommander/redis-commander:latest
    environment:
      - REDIS_HOSTS=local:redis:6379
    ports:
      - "8081:8081"
    depends_on:
      - redis

networks:
  postgres:
    driver: bridge
